//#-hidden-code
//
//  See LICENSE folder for this template’s licensing information.
//
//  Abstract:
//  The Swift file containing the source code edited by the user of this playground book.
//
//#-end-hidden-code
//: # Simple Q&A System
//: Knowledge graphs have the potential to be used in many areas, currently the knowledge graph is mainly used in search engines, intelligent Q&A, big data analytics, language translation and language understanding, and Internet of Things.
//:
//: A simple question and answer system can be constructed from the data generated by the knowledge graph of the countries. The working logic of this system is to get the information of **secondEntity** on the basis of **firstEntity** and **relation**. The data format stored in the question and answer system is roughly as follows.
//: - - -
//: ...
//:
//: "Countries" "contain" "France"
//:
//: "France" "Capital" "Paris"
//:
//: "France" "Official Language" "French"
//:
//: "France" "National Anthem" "LaMarseillaise"
//:
//: "Paris" "Landmark" "Eiffel Tower"
//:
//: ...
//: - - -
//: In the engineering field, the data of the knowledge graph will be stored in the database, and the data in the database needs to be cleaned and sorted. With the help of artificial intelligence technology, we can grab information from text or images to build a multi-dimensional knowledge graph. In general, the logic that needs to be processed in the real knowledge graph will be much more complicated, and the amount of data that needs to be processed will also be astonishing. If you are interested in the knowledge graph, you can learn more about the knowledge graph from the Internet.
//: ### Disclaimer:
//: Some of the code was inspired by, and modified from, a tutorial written by Warren Burton on the Raywenderlich website.
//:
//: Intro background music is from Royalty Free, free music library, provided by Purple Planet Music.
//:
//: The design of “First Taste of Knowledge Graph” playground was done by Stephen Fang (Xuanmiao Fang).
//:
//: This playground book is licensed under MIT License. “First Taste of Knowledge Graph” is a project by Stephen Fang (Xuanmiao Fang).
